import fs from'node:fs/promises';import path from'node:path';
const key=process.env.USPTO_API_KEY;if(!key){console.log('USPTO_API_KEY is not configured; keeping the existing sample data and skipping live sync.');process.exit(0);}
const configPath=process.env.PORTFOLIO_CONFIG||'config/portfolio.json';let cfg;try{cfg=JSON.parse(await fs.readFile(configPath,'utf8'))}catch{throw new Error('Create config/portfolio.json from config/portfolio.example.json.');}
const digits=v=>String(v||'').replace(/\D/g,'');const apps=[...new Set((cfg.applications||[]).map(digits).filter(Boolean))];const limit=Math.min(2000,Math.max(1,Number(cfg.maximum_results)||500));if(!apps.length&&!cfg.search_query)throw new Error('Add application numbers or a USPTO search_query to config/portfolio.json.');
const endpoint='https://api.uspto.gov/api/v1/patent/applications/search';const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function request(body){for(let n=0;n<4;n++){const r=await fetch(endpoint,{method:'POST',headers:{'X-API-KEY':key,'Content-Type':'application/json',Accept:'application/json','User-Agent':'PatentDeadlineCalendar/2.0'},body:JSON.stringify(body)});if(r.ok)return r.json();if(![429,500,502,503,504].includes(r.status))throw new Error('USPTO request failed with HTTP '+r.status);await sleep(1000*2**n)}throw new Error('USPTO request failed after retries.');}
const bags=[];for(let i=0;i<apps.length;i+=40){const part=apps.slice(i,i+40);const q='applicationNumberText:('+part.join(' OR ')+')';const d=await request({q,pagination:{offset:0,limit:part.length}});bags.push(...(d.patentFileWrapperDataBag||[]));await sleep(250)}
if(cfg.search_query){for(let offset=0;offset<limit;offset+=100){const d=await request({q:cfg.search_query,pagination:{offset,limit:Math.min(100,limit-offset)}});const rows=d.patentFileWrapperDataBag||[];bags.push(...rows);if(rows.length<100)break;await sleep(250)}}
const addMonths=(v,n)=>{const d=new Date(String(v).slice(0,10)+'T12:00:00Z');if(Number.isNaN(d.valueOf()))return'';d.setUTCMonth(d.getUTCMonth()+n);return d.toISOString().slice(0,10)};const text=v=>String(v||'').trim();
function metadata(b){return b.applicationMetaData||{}}function appNumber(b){const m=metadata(b);return digits(b.applicationNumberText||m.applicationNumberText)}function title(b){const m=metadata(b);return text(m.inventionTitle||m.inventionSubjectMatterText)}function inventors(b){const m=metadata(b);return(m.inventorBag||[]).map(x=>text(x.inventorNameText||[x.firstName,x.middleName,x.lastName].filter(Boolean).join(' '))).filter(Boolean).join('; ')}
function eventRows(b){const direct=b.eventDataBag||b.applicationEventBag||metadata(b).eventDataBag||[];return Array.isArray(direct)?direct:[]}
const events=[];for(const b of bags){const m=metadata(b),application_number=appNumber(b),common={application_number,patent_number:digits(m.patentNumber),title:title(b),inventor_list:inventors(b),filing_date:text(m.filingDate).slice(0,10)};for(const e of eventRows(b)){const label=text(e.eventDescriptionText||e.eventCodeDescriptionText||e.eventDescription),eventDate=text(e.eventDate||e.eventDateText).slice(0,10),low=label.toLowerCase();if(!eventDate||!/(non.?final|final rejection|restriction requirement|ex parte quayle)/i.test(label))continue;const due=addMonths(eventDate,3);events.push({...common,id:application_number+'-'+eventDate+'-'+events.length,type:'prosecution',due_date:due,source_event:label,grace_end:addMonths(eventDate,6),is_estimated:true})}if(common.patent_number&&m.grantDate){[['3.5y',42],['7.5y',90],['11.5y',138]].forEach(([stage,months])=>events.push({...common,id:common.patent_number+'-'+stage,type:'maintenance',due_date:addMonths(m.grantDate,months),source_event:stage+' maintenance fee',stage,is_estimated:true}))}}
const unique=[...new Map(events.filter(e=>e.due_date).map(e=>[e.id,e])).values()].sort((a,b)=>a.due_date.localeCompare(b.due_date));const output={organization_name:text(cfg.organization_name)||'Patent Portfolio',generated_at:new Date().toISOString(),data_mode:'live',source:'USPTO Open Data Portal',events:unique};await fs.mkdir(path.dirname('public/data/deadlines.json'),{recursive:true});await fs.writeFile('public/data/deadlines.json',JSON.stringify(output,null,2)+'\n');console.log('Wrote '+unique.length+' public deadline events from '+bags.length+' application records.');
